// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("DataAccess.Questions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Option2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Option3")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Option4")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QnInWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Option1")
                        .IsUnique()
                        .HasFilter("[Option1] IS NOT NULL");

                    b.HasIndex("Option2")
                        .IsUnique()
                        .HasFilter("[Option2] IS NOT NULL");

                    b.HasIndex("Option3")
                        .IsUnique()
                        .HasFilter("[Option3] IS NOT NULL");

                    b.HasIndex("Option4")
                        .IsUnique()
                        .HasFilter("[Option4] IS NOT NULL");

                    b.ToTable("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
